version: '3.9'

services:
  db:
    container_name: db
    image: mysql:8.0.34
    ports:
      - "3306:3306"
    env_file:
      - db.env
    restart:
      always
    volumes:
      - ./tmp/mysql:/var/lib/mysql:delegated
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 2s
      timeout: 1s
      retries: 5
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./Dockerfile
      target: builder
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
    command: ["reflex", "-r", "^.*.go$", "-s", "go", "run", "./server.go"]
    tty: true
    volumes:
      - .:/app:cached
    env_file:
      - db.env
  ui:
    container_name: ui
    build:
      context: ./ui
      dockerfile: ./Dockerfile
      target: builder
    ports:
      - 3000:3000
    command: ["sh", "-c", "npm run dev"]
    volumes:
      - type: volume
        source: node_modules
        target: /app/node_modules
        volume:
          nocopy: true
    environment:
      NODE_ENV: development
    depends_on:
      - db
      - api

volumes:
  node_modules:
  yarn_cache:
