version: '3.9'

services:
  db:
    container_name: db
    image: mysql:8.0.34
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nulledge_local
      MYSQL_USER: nulledge
      MYSQL_PASSWORD: password
    restart:
      always
    volumes:
      - ./tmp/mysql:/var/lib/mysql:delegated
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./Dockerfile
      target: builder
    ports:
      - 8080:8080
    depends_on:
      - db
    command: ["reflex", "-r", "^.*.go$", "-s", "go", "run", "./server.go"]
    tty: true
    volumes:
      - .:/app:cached
    environment:
      MYSQL_USER: nulledge
      MYSQL_PASSWORD: password
      MYSQL_TABLENAME: nulledge_local
      MYSQL_ADDR: db
      MYSQL_PORT: 3306
