version: '3'

tasks:
  logs:
    desc: 'show containers logs'
    cmds:
      - docker compose logs -f
  run:
    desc: 'start dev containers'
    cmds:
      - docker compose up -d
  down:
    desc: 'stop dev containers'
    cmds:
      - docker compose down
  test:
    desc: 'run test'
    cmds:
      - go test ./...
  gqlgen:
    desc: 'run gqlgen code genrater'
    cmds:
      - go run -mod=mod github.com/99designs/gqlgen generate
    silent: false
