package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"
	"fmt"

	"github.com/tomato3713/nulledge/graph/model"
)

// CreatePage is the resolver for the createPage field.
func (r *mutationResolver) CreatePage(ctx context.Context, input model.NewPage) (*model.Page, error) {
	panic(fmt.Errorf("not implemented: CreatePage - createPage"))
}

// Pages is the resolver for the pages field.
func (r *queryResolver) Pages(ctx context.Context) ([]*model.Page, error) {
	panic(fmt.Errorf("not implemented: Pages - pages"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
