package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"
	"fmt"

	"github.com/tomato3713/nulledge/graph/model"
)

// Format is the resolver for the format field.
func (r *pageResolver) Format(ctx context.Context, obj *model.Page) (model.MarkupLanguage, error) {
	panic(fmt.Errorf("not implemented: Format - format"))
}

// User is the resolver for the user field.
func (r *pageResolver) User(ctx context.Context, obj *model.Page) (*model.User, error) {
	panic(fmt.Errorf("not implemented: User - user"))
}

// Page returns PageResolver implementation.
func (r *Resolver) Page() PageResolver { return &pageResolver{r} }

type pageResolver struct{ *Resolver }
